### ISSUE TITLE
Update the Wiki personal pages

### ISSUE THREAD

**Issue by mhrfky** [bounswe/bounswe2020group3#127]
Newcomers should upload their personal pages and the ones that are not with us this semester shall be updated as so.

**Comment by mhrfky** [comment]
Mustafa Küçük,  Hande Karabul, Fatih Akgöz has been strikedthrough to show that these old members has left this group.

**Comment by adilnumancelik2017400198** [comment]
I created my wiki page.

**Comment by merttahran** [comment]
created personal wiki page and updated sidebar and wiki homepage

**Comment by buseg** [comment]
created personal wiki page and updated sidebar

**Comment by ynskardas** [comment]
created personal wiki page and updated sidebar and wiki homepage

**Comment by liberbey** [comment]
created my personal wiki page, updated sidebar and added myself to readme.

**Comment by ybedirhanpak** [comment]
I've updated my personal wiki page

**Comment by alifurkanbudak** [comment]
I've updated my personal wiki page

**Comment by emirhanyasin** [comment]
I have updated my personal wiki page.

**Comment by emirhanyasin** [comment]
Every team member has his/her personal wiki pages updated, last by me.
