### ISSUE TITLE
Reviewing requirements	

### ISSUE THREAD

**Issue by mhrfky** [bounswe/bounswe2020group3#135]

**Comment by buseg** [comment]
1.2.4. Profile Page
1.2.4.1 System shall provide personal profile pages to registered users. (TODO : Delete)
1.2.4.2 System shall ensure that private profile pages are displayed to followers.
1.2.4.3 System shall ensure that guest users can only view ten profile pages per day. (TODO : Delete)
1.2.4.4 System shall provide necessary mechanism for users to link their profile page with Google Scholar or ResearchGate.

Why are there TODO's here, should we delete these requirements?

**Comment by buseg** [comment]
Deleted the items marked with TODO: Delete after @yusufbayam confirmed they were marked as unnecessary in a customer meeting.

**Comment by merttahran** [comment]
items 1.1.2.5 and 2.3.1 were corrected

**Comment by adilnumancelik2017400198** [comment]
A grammar error in 1.1.4.1 is found, and corrected.

**Comment by buseg** [comment]
I think we can say we are done with the review, I'm closing now.
