### ISSUE TITLE
Send consent request for section 2

### ISSUE THREAD

**Issue by ybedirhanpak** [bounswe/bounswe2020group3#136]
* **Project: GENERAL**

* **I'm submitting a**
- [x] documentation request

* **Briefly describe the issue.**

Everyone must send consent request in order to switch to the section 2.

* **Additional information**

Please check this box when you sent your consent.

- [x] Mahir Efe KAYA
- [x] Ahmet Emir Kocaağa
- [x] Ramazan Koç
- [x] Buse Giledereli
- [x] Yunus Kardaş
- [x] Ali Furkan Budak
- [x] Barış Başmak
- [x] Furkan Cansever
- [x] Yusuf Bayam
- [x] Yahya Bedirhan Pak
- [x] Adil Numan Çelik
- [x] Ahmet Mert Tahran
- [x] Emirhan Yasin Çetin

* **Deadline for resolution:** 

**05.11.2020**

**Comment by mhrfky** [comment]
I sent consent and waiting
