### ISSUE TITLE
Setting gitignore file

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2020group3#138]
* **Project: GENERAL / FRONTEND / BACKEND / ANDROID**

* **I'm submitting a **
  - [ ] feature request

* **Briefly describe the issue.**

gitignore file should be configured.

* **Additional information**

Files like virtual environment should not be commited.

* **Deadline for resolution:** 

05.11.2020

**Comment by cnsvr** [comment]
I realized that while I pushing my codes into Github, there are some cache files in repository although these files extensions are in .gitignore. I don't know it will be a problem for us, but cache files don't look good in repo :).  Can you check again these files?  [Here](https://github.com/bounswe/bounswe2020group3/tree/backend/backend/backend/__pycache__)

**Comment by alifurkanbudak** [comment]
@liberbey has removed the pycache folder from the repo, now its done
