### ISSUE TITLE
Exploring code analysis tools

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2020group3#139]
* **Project:  BACKEND**

* **I'm submitting a**
  - [ ] documentation request

* **Briefly describe the issue.**

All should search about code analysis tools like pylint, bandit and github action.

* **Deadline for resolution:** 

05.11.2020

**Comment by ybedirhanpak** [comment]
I think you should select the PROJECT type :)

**Comment by liberbey** [comment]
Good point :)

**Comment by liberbey** [comment]
@ynskardas can you complete this issue? You can look for django-pylint, bandit and github action. The purpose is having an automated tool for security check and coding analysis.

**Comment by ynskardas** [comment]
I am transfered Frontend Group and this is not needed
