### ISSUE TITLE
Create requirements from the project description

### ISSUE THREAD

**Issue by mhrfky** [bounswe/bounswe2020group3#14]
Create requirements wiki page and add the requirements

**Comment by alifurkanbudak** [comment]
Created and filled Sign Up, Sign In, Academic Collaboration, Project Management and Profile titles.
Also added the page to the sidebar under the new Project sidebar title.

**Comment by rambo250** [comment]
Created and filled Platform titles.

**Comment by ybedirhanpak** [comment]
Search requirements added.

**Comment by Mustafakck** [comment]
GDPR and KVKK requirements generalized and added as Legitimate Requirements.

**Comment by ybedirhanpak** [comment]
I think the goal of this issue is completed, since we created the basic structure of requirements according to the project description. Further improvements will be held under other, more detailed issues. This issue can be closed.
