### ISSUE TITLE
[Front-End] Profile Page Editing

### ISSUE THREAD

**Issue by Chuchichachtli** [bounswe/bounswe2020group3#148]
Related Requirements: 
* 1.1.5.1. Users shall be able to edit their profile information.
* 1.1.5.1.1. Users shall be able to change or add new photos for their profiles
* 1.1.5.1.2. Users shall be able to change their shown biological gender with one of the given next: 'male','female','do not want to share'
* 1.1.5.1.3. Users shall be able to decide whether to give the information of their age or not
* 1.1.5.1.4. Users shall be able to share their interests unrelated to their academic profession such as cosmology, astrology in their profiles.

**Comment by emirhanyasin** [comment]
Done partially, will be finished with the rest of the functionalities after review 'till the end of this week
