### ISSUE TITLE
Deciding Project Name and logo

### ISSUE THREAD

**Issue by yusufbayam** [bounswe/bounswe2020group3#15]
Everyone will leave comment about their opinions.

**Comment by ybedirhanpak** [comment]
Benim isim önerilerim: 
* Papershare
* Future
* BeyondPaper

**Comment by ybedirhanpak** [comment]
## Logo önerilerim:

![Logo-1](https://github.com/bounswe/bounswe2020group3/blob/master/logos/beyond_paper_1.png?raw=true)

![Logo-2](https://github.com/bounswe/bounswe2020group3/blob/master/logos/beyond_paper_2.png?raw=true)

![Logo-3](https://github.com/bounswe/bounswe2020group3/blob/master/logos/beyond_paper_3.png?raw=true)

![Logo-4](https://github.com/bounswe/bounswe2020group3/blob/master/logos/beyond_paper_4.png?raw=true)

**Comment by rambo250** [comment]
Gezegenli olan logolar güzel olmuş. İsim olarak BeyondPaper güzel gibi.

**Comment by cnsvr** [comment]
Biraz araştırıp bunları buldum, aklıma geldikçe ekleme yaparım.😎
PaperLayer
PaperVenture
PaperTorch
Sheett

**Comment by Mustafakck** [comment]
Bence logolar baya hoş, isim olarak PaperLayer yapsak güzel olur :)

**Comment by ybedirhanpak** [comment]
Başka önerileri olan yoksa mevcut seçenekler için bir doodle açabiliriz.

**Comment by alifurkanbudak** [comment]
![Logo_Name](https://user-images.githubusercontent.com/40214943/75911213-45414c00-5e60-11ea-8d8c-9772c234a01d.png)

**Comment by alifurkanbudak** [comment]
![Logo_Name](https://user-images.githubusercontent.com/40214943/76151432-1e844f00-60c6-11ea-9bab-747372f5969d.png)
versiyon 2. slogan da ekledim, kim olursan ol yine collaborate'in ingilizcesini bu şekilde düşündüm

**Comment by alifurkanbudak** [comment]
![Logo_Name](https://user-images.githubusercontent.com/40214943/76151557-5f309800-60c7-11ea-99cc-02fa11259903.png)
spamlıyormuşum gibi oldu ama bu daha iyi bir çeviri gibi

**Comment by ybedirhanpak** [comment]
We've decided it to be PaperLayer. Do you have any other logo ideas?
