### ISSUE TITLE
Documentation for the Upcoming APIs

### ISSUE THREAD

**Issue by Chuchichachtli** [bounswe/bounswe2020group3#150]
* **Project: BACKEND**

* **I'm submitting a documentation request**

* **Briefly describe the issue.**

We need documentation for the APIs that are being implemented ahead of time so that Front-End and Android teams can 
develop their tasks more easily and the communication overhead is reduced.

* **For feature requests, please explain the expected functionality.**

We need a wiki page for API documentations and we need to have an up to date descriptions of the finished APIs as well as the ones that are being developed at the current time. 

* **Deadline for resolution:** 

As Soon As Possible

**Comment by cnsvr** [comment]
We decided to use Swagger for API documentation as the backend team if it is okay for the frontend and android team.  You will be able to see and use any controllers, any endpoints we implemented with Swagger. If it is wanted for milestone, we prepare a wiki page. For example, [click here.](https://www.idevnews.com/views/images/uploads/general/swagger-ui.png)

**Comment by Chuchichachtli** [comment]
It looks pretty good, if the Android team is also Ok with this we can definitely use it. @yusufbayam

**Comment by yusufbayam** [comment]
Swagger is okey with us too.

**Comment by cnsvr** [comment]
I implemented the Swagger API documentation page. 
You can use all controllers or endpoints we implemented after setting up backend environment.
The swagger page is  at **localhost:8000/swagger**
Also, there is another page called 'redoc' for documentation at **localhost:8000/redoc**

If it is okay for you, this issue can be closed.

**Comment by Chuchichachtli** [comment]
Thanks for your efforts, I think the issue is resolved. 👍
