### ISSUE TITLE
Setting up Swagger 

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2020group3#152]
* **Project: BACKEND**

* **This is a: DOCUMENTATION REQUEST**

* **Description of the issue**

Swagger will be used for automated API descriptions.

* **Additional information**

Swagger is an automated tool for APIs.

* **Deadline for resolution:** 

07.11.2020

**Comment by cnsvr** [comment]
It's done 👍 . I opened PR for this implementation.
