### ISSUE TITLE
Implementing authentication system

### ISSUE THREAD

**Issue by alifurkanbudak** [bounswe/bounswe2020group3#154]
* **Project: (select one) BACKEND**

* **This is a: (select one) FEATURE REQUEST**

* **Description of the issue**

An authentication system will be implemented in Django

* **For feature requests: Expected functionality of the requested feature**

Signup, login, logout, and reset password endpoints will be implemented.
These requirements will be satisfied: 1.1.1.1, 1.1.2.1, 1.1.2.3, 1.1.2.5. 

* **Deadline for resolution:** 

November 10, 2020

**Comment by adilnumancelik2017400198** [comment]
https://medium.com/swlh/build-your-first-rest-api-with-django-rest-framework-e394e39a482c

This tutorial will be followed.

**Comment by adilnumancelik2017400198** [comment]
https://dj-rest-auth.readthedocs.io/en/latest/introduction.html#

This package will be used.

**Comment by alifurkanbudak** [comment]
Implemented 4 endpoints with @adilnumancelik2017400198 without the library mentioned above. PR merged
