### ISSUE TITLE
Deciding Customer Meeting Questions

### ISSUE THREAD

**Issue by ybedirhanpak** [bounswe/bounswe2020group3#18]
### Customer Meeting Date
**Date:** 06.03.2020
**Time:** 11:00
**Place:** BM Lab 46
### Question Sheet
**1.Will there be any system admin that has a general control over the application. If so, what are the capabilities of the admin?**
   1.1 Accessing database,
    1.2 Blocking unrelated material,
    1.3 Deleting inappropriate content,
    1.4 Banning users, permanently or temporarily,
    1.5 Shutting down a project in case of violation of a copyright
 **2.Will there be any hierarchy between collaborators, for example some of them are project owners and the others are only contributors. If so what will be these project owners' authority over the others:**
    2.1. Inviting people to project, accept contribution submissions
    2.2. Changing project title, due date, accessibility, description, tags.
    **3.Will searching be done in any category, under a single search results list, or will the options be mandatory such as "search in projects", "search in users", "search in academic events".**
    3.1. User searches keyword "Burak" and these results come up: "Burak Kaya" and "Statistical project about the use of name Burak in Turkey"
    3.2. User searches keyword "Burak" and selects "search in users". Only "Burak Kaya" shows up.
    **4.Will there be any difference between creating a post and project. Should users create projects and posts separately, If there will be a post system which of these will be supported:**
    4.1. Posting video, picture, simple text, audio record
    4.2. Announcement of an academic event ( where other people can select participating options: yes, no, maybe )
    4.3. Posting with attaching it to a project
    4.4. Posting and not attaching it to any project.
    **5.Will there be any restriction in uploaded files into projects such as 1MB, 10MB, 1GB ?**
    **6.Will users be logged in via other platforms such as "Login with Facebook, Linkedin, ResearchGate".**
    6.1. If they log in system with linkedin, should they also log in the same account with email or with any other platform ?
   **7.What will be collaboration permissions of projects? Will there be any open-source projects that anyone can contribute or will all collaborations need requests?**

**Comment by ybedirhanpak** [comment]
What will be collaboration permissions of projects? Will there be any open-source projects that anyone can contribute or will all collaborations need requests?

**Comment by alifurkanbudak** [comment]
Should there be a difference between posting an academic collaboration post vs. a project management post?

**Comment by ybedirhanpak** [comment]
These are the questions that we decided on meeting:
1- Will there be any system admin that has a general control over the application
2- Will there be any hierarchy between collaborators, for example some of them are authors or project owners and the others are only contributors, so that some tasks can be done by only project owners: inviting people to project, accept contribution submissions, change project due date.
3- When one is searching from search bar, will there be categories to search  within immediately with a dropdown. Should the classification (search for users, search for projects, search for academic events) of search be done at the start of search or via a filter box, after the search results are shown.
4- Will there be any difference between creating a post and project. Should users post a video, picture, simple text about an academic research with attaching it to a project or not attaching to anything, other than creating a project

**Comment by ybedirhanpak** [comment]
According to the project description 
>There should be a tab for preparing the submission document or article, which can be accessed by the collaborators simultaneously.

**Will the project management done by a version control system like git or simultaneous document editing like google docs ?**

**Can a profile page be private in a way that details about the user only shown to his/her followers ?**

**Will there by any special stage system in projects such that "Looking for collaboration" -> "In Progress" -> "Completed", or the status of projects will be specified with tags ?**

**Will there be any versioning in projects such as semantic versioning ? [Semantic Versioning](https://semver.org/)**

**Comment by alifurkanbudak** [comment]
Customer meeting completed
