### ISSUE TITLE
Creating Scenario 2

### ISSUE THREAD

**Issue by ybedirhanpak** [bounswe/bounswe2020group3#19]
## Description
In scenario 2, user will search for a project and check its details. If user is interested in project, he/she sends a request to collaborate.

### Scenario Format
* User photo, name and persona
* Preconditions
* User story
* Acceptance Criteria

### Wiki Page
[User Stories and Scenarios](https://github.com/bounswe/bounswe2020group3/wiki/User-Stories-and-Scenarios)

### Due to
03.03.2020

**Comment by ybedirhanpak** [comment]
### 27.02.2020 Updates

### Collaborators
* Ramazan Koç
* Yahya Bedirhan Pak

### Added but Preview Needed
* User photo, name and persona
* Preconditions
* User story

**Comment by cnsvr** [comment]
Ben bi problem göremedim fakat bazı kategorilerde değişiklik yaptım.Acceptance Criteria da numaralandırmalarda değişiklik yapabilir misin ya da requirements lara ekleme yapabilirsin.

**Comment by ybedirhanpak** [comment]
Creation of scenario 2 has been done. This issue can be closed.
