### ISSUE TITLE
[Backend] Create CD Configuration

### ISSUE THREAD

**Issue by ybedirhanpak** [bounswe/bounswe2020group3#237]
* **Project: BACKEND**

* **This is a: FEATURE REQUEST**

* **Description of the issue**

There should be a continuous delivery configuration, Github action workflow,  which includes:
- Deploying docker image to AWS

* **Deadline for resolution:** 

22.11.2020

**Comment by cnsvr** [comment]
I will search for the steps of deploying docker image to AWS and Github Actions. See you at 19 November. 👀
