### ISSUE TITLE
We need to come up with a logo for paperlayer

### ISSUE THREAD

**Issue by Chuchichachtli** [bounswe/bounswe2020group3#241]
* **Project:  GENERAL**
We need to design a logo for paperlayer for our demo.
It would be great if everyone could contribute to this issue by either designing and posting a logo or coming up with ideas. 

* **Deadline for resolution:** 
22.11.2020

**Comment by liberbey** [comment]
Is there anyone familiar with designing logos? She or he can lead us about this.

**Comment by buseg** [comment]
Ideas: A paper-boat or origami-style logo could be nice

**Comment by buseg** [comment]
![PaperLayer](https://user-images.githubusercontent.com/32413631/99410978-260e2000-2904-11eb-9040-80bbf6fabfc3.png)
I had something like this in mind (Did this dummy version in Adobe Spark, I like that it also looks like Paper-Lover)

**Comment by alifurkanbudak** [comment]
### I am reminding you that this group rejected this might suggestion:

![image](https://user-images.githubusercontent.com/40214943/99414443-df222980-2907-11eb-880d-d2233ec31301.png)

**Comment by adilnumancelik2017400198** [comment]
I appreciate how some of you embrace this project and try to make every detail as likeable as you can but in order to not create any further conflict on this issue I won't offer an alternative logo.

**Comment by ybedirhanpak** [comment]
As @buseg suggested in discord channel, this looks fine for logo I think:
![Logo](https://cdn.discordapp.com/attachments/678569359031140376/778279740443328542/unknown.png)

**Comment by Chuchichachtli** [comment]
I feel like the airplane logo ismore suitable to our app than the paper boat because it's more simplistic.

**Comment by buseg** [comment]
I'm also more inclined towards this one

**Comment by ybedirhanpak** [comment]
We selected this logo
![](https://media.discordapp.net/attachments/678569359031140376/779076199753711637/paper-plane.png)
