### ISSUE TITLE
Requirements will be reviewed(1.1.1 to 1.1.5)

### ISSUE THREAD

**Issue by cnsvr** [bounswe/bounswe2020group3#26]

**Comment by cnsvr** [comment]
I made some changes up to 1.1.5. Some of them may vary. We can make changes to the next meeting before we send the first version, and we can probably close this issue after that.

**Comment by ybedirhanpak** [comment]
Since we made a new work distribution over requirements, you may change this issue accordingly or create a new one.

[Meeting Notes 4](https://github.com/bounswe/bounswe2020group3/wiki/Meeting-Notes%234-(04.03.2020))

**Comment by cnsvr** [comment]
I closed the issue because of new work distribution over requirements at last meeting.
