### ISSUE TITLE
Mockups for scenario 2 will be created.

### ISSUE THREAD

**Issue by ybedirhanpak** [bounswe/bounswe2020group3#28]
## Description
Mockups for scenario 2 in [User Stories and Scenarios](https://github.com/bounswe/bounswe2020group3/wiki/User-Stories-and-Scenarios) will be created and added to wiki.

### Wiki Page
[Mockups](https://github.com/bounswe/bounswe2020group3/wiki/Mockups) 

### Due to
03.03.2020

**Comment by ybedirhanpak** [comment]
### Update
Mockups created and uploaded to [bounswe2020group3/mockups/](https://github.com/bounswe/bounswe2020group3/tree/master/mockups). 

### Contributors
* Mahir Efe Kaya
* Yahya Bedirhan Pak

**Comment by rambo250** [comment]
Mockup of scenario 2 is added to wiki page. Review needed. We can close the issue after ther review.

**Comment by ybedirhanpak** [comment]
It seems fine @rambo250 , This issue can be closed.
