### ISSUE TITLE
Review System Requirements

### ISSUE THREAD

**Issue by yusufbayam** [bounswe/bounswe2020group3#32]
### Description :
System requirements should be reviewed according to project description, feedback from customer and meeting notes. These topics should be included :
* Search Engine
* Recommendation
* Notifications
* Profile Page
* Project Management

#### Update (06.04.2020)
System requirements will be reviewed according to the feedbacks.

### Due Date  (updated) : 07.04.2020

**Comment by yusufbayam** [comment]
* System Requirements created from scratch.
* Added requirements: Search Engine, Recommendation, Notifications, Profile Page, Project Management .

**Comment by cnsvr** [comment]
Maybe you can add a feature that keeps a history search in users' search bar so that the user can easily view their search histories and search for saved searches without retyping them.

**Comment by cnsvr** [comment]
In 1.2.5.1 there is a state that is "Open for collaborators", but we used  "seeking for collaborators" for project states in 1.1.3 and 1.1.10 and if we are talking about the same thing, we can change and do the same thing.

**Comment by ybedirhanpak** [comment]
> In 1.2.5.1 there is a state that is "Open for collaborators", but we used "seeking for collaborators" for project states in 1.1.3 and 1.1.10 and if we are talking about the same thing, we can change and do the same thing.

Since projects can be private during the stage that project creators invite others, I think "Open for collaborators" doesn't represent the private status. I recommend that it's name should be "Open for collaborators" for public projects and "Seeking for collaborators" for private project.

**Comment by ybedirhanpak** [comment]
We will review again according to the feedbacks.
