### ISSUE TITLE
Gmail credentials are publicly available

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group3#329]
Dear members of Group 3,

Anyone with an Internet connection is able to see the password for bounswe2020group3@gmail.com via [settings.py](https://github.com/bounswe/bounswe2020group3/blob/master/backend/backend/settings.py).

Is it the right approach to store credentials?

(Note: I am not able to assign everyone since there can be at most 10 assignees.)

**Comment by liberbey** [comment]
It’s definetely not the right approach. We will fix it as soon as possible, thank you very much for mentioning.

**Comment by cnsvr** [comment]
I fixed the issue and opened pr #330. After that, we will use the AWS Secret Manager for secrets in the project. I prepared a [wiki page](https://github.com/bounswe/bounswe2020group3/wiki/Secrets-Management) for secret management in case we need it in the following development period. After pr is approved, the issue can be closed.
