### ISSUE TITLE
[Front-End] Adding Milestone Lists to the Profile Page

### ISSUE THREAD

**Issue by Chuchichachtli** [bounswe/bounswe2020group3#387]
* **Project: FRONTEND**

* **This is a:  FEATURE REQUEST**

* **Description of the issue**
We want to add milestones to the profile page so that the user will have access to them and see them clearly. 
Even better if we sort them w.r.t. their dates. 

* **For feature requests: Expected functionality of the requested feature**
We need the milestones of a user, sorted with respect to their due dates. 
Would be especially good if we could pull them with adding the Token to the header and simply use a get request

Ex. which inputs should be given and what outputs are expected for an API endpoint feature request.
INPUT : User token / User id 
OUTPUT: User milestones. 

* **Deadline for resolution:** 

21.12.2020

**Comment by cnsvr** [comment]
An authenticated user can access all their own milestones in a sorted way with the date.
PR: #393 
GET : /api/milestones/get_user_milestones/
OUTPUT : { 'result': List of Milestones }
