### ISSUE TITLE
[Front-End] Choosing Colours for Front-End

### ISSUE THREAD

**Issue by Chuchichachtli** [bounswe/bounswe2020group3#427]
* **Project: FRONTEND**

* **This is a: FEATURE REQUEST**

* **Description of the issue**
We need to find good colours for the front-end. 
Especially important ones : 
* Sidebar Colour
* Navigation Bar Colour
* Website Background Colour

* **Deadline for resolution:** 
27.12.2020 ---> Before the Release

**Comment by liberbey** [comment]
Background color is done. Will change sidebar color soon and open a PR.

**Comment by Chuchichachtli** [comment]
All tasks are done. I'm closing the issue
