### ISSUE TITLE
Review the use-case diagram

### ISSUE THREAD

**Issue by mhrfky** [bounswe/bounswe2020group3#51]
**Description:**

Use-case diagram will be reviewed according to feedback for the diagrams.

**Wiki Page** : [Use Case Diagram](https://github.com/bounswe/bounswe2020group3/wiki/Use-Case-Diagram) 

**Due Date**  : 07.04.2020

**Comment by FatihAkgoz** [comment]
I rewieved the diagram. Found no problem.

**Comment by cnsvr** [comment]
Done. 👍
