### ISSUE TITLE
Deciding on which APIs we'll use

### ISSUE THREAD

**Issue by Chuchichachtli** [bounswe/bounswe2020group3#62]
We need to find APIs that'll be beneficial for us in the upcoming stages of our project.

**Comment by Chuchichachtli** [comment]
One idea that came to my mind is to  get headline news from an API redirect it to another API that'll determine the topic and keywords of the API.
In this way we'll find scientific or Covid-19 related news and we can show their titles and provide the links to the news in our feed / homepage.

**Comment by cnsvr** [comment]
This is about creating our own API.
At the customer meeting, we talked about events s.t. the conferences, journals, or Tubitak projects and decided to show upcoming events at the [right side-bar of the home page](https://github.com/bounswe/bounswe2020group3/blob/master/mockups/Home_Page_with_user_login_last_v1.png) (maybe for now events of May).
Also, we talked that we could enter these data by hand and I think with basic UI on left side we can show them. This is my opinion :)  We can talk about this at the meeting.

Upcoming Events -> https://www.call4paper.com/listByDate?type=event&year=2020&month=5&count=submission

**Comment by mhrfky** [comment]
Since our subject and our objective is already determined, we should move towards it while working on our first api. So I believe, if we could use researchgate and googlescholar api to retrieve information about the users, it would be very beneficial to our project.

**Comment by rambo250** [comment]
In later stages of our project, we can need usage data from users to observe how they use our website. So, we can use google analytics API to collect data from users to see how our websited being used or we can see if our system works well or not.

**Comment by Chuchichachtli** [comment]
Thinking about what we can do with mhrfky's suggestion, we can perhaps, import a user's papers and projects from google scholar and show in our system.
