### ISSUE TITLE
Deciding the endpoints we will implement in initial release

### ISSUE THREAD

**Issue by mhrfky** [bounswe/bounswe2020group3#63]
We should decide the endpoints to start our first api. Therefore we should decide easy to implement endpoints to practice and do a good start

**Comment by cnsvr** [comment]
At the customer meeting, we talked about events s.t. the conferences, journals, or Tubitak projects and decided to show upcoming events at the [right side-bar of the home page](https://github.com/bounswe/bounswe2020group3/blob/master/mockups/Home_Page_with_user_login_last_v1.png) (maybe for now events of May).
Also, we talked that we could enter these data by hand and I think with basic UI on left side we can show them.  We can talk about this at the meeting.

Upcoming Events -> https://www.call4paper.com/listByDate?type=event&year=2020&month=5&count=submission

**Comment by mhrfky** [comment]
We could and I believe we should start with log in and register endpoints at first. In parallel we could also start with project creation, and project editing. If time would allows us to do, we could also try to implement collaboration and follow endpoints

**Comment by yusufbayam** [comment]
We have decided on endpoint that will be implemented at group meeting#13.
