### ISSUE TITLE
Data Generation 

### ISSUE THREAD

**Issue by liberbey** [bounswe/bounswe2020group3#688]
* **Project: GENERAL **

* **This is a: DOCUMENTATION REQUEST**

* **Description of the issue**

Everyone will create realistic data.

- [ ] @liberbey 
- [ ] @ynskardas 
- [x] @adilnumancelik 
- [x] @buseg 
- [ ] @Chuchichachtli 
- [x] @merttahran 
- [ ] @emirhanyasin 
- [ ] @alifurkanbudak 
- [x] @cnsvr 
- [ ] @mhrfky 
- [ ] @ynskardas 
- [x] @rambo250 
- [x] @ybedirhanpak 

* **Deadline for resolution:** 

30.01.2021

**Comment by Chuchichachtli** [comment]
gg wp
