### ISSUE TITLE
Watch Git For Ages 4 And Up

### ISSUE THREAD

**Issue by yusufbayam** [bounswe/bounswe2020group3#9]
https://www.youtube.com/watch?v=1ffBJ4sVUb4

- [ ] Yahya Bedirhan Pak
- [ ] Furkan Cansever
- [ ] Ramazan Koç
- [ ] Mahir Efe Kaya 
- [ ] Hande Karabul
- [ ] Mustafa Küçük
- [ ] Ali Furkan Budak
- [ ] Yusuf Bayam
- [ ] Fatih Akgöz

**Comment by yusufbayam** [comment]
Gençler bu issue çok effort istiyor, değiştirsek mi acaba?

**Comment by mhrfky** [comment]
herkes izledim desin. gerektikçe doc bakarız zaten

18 Şub 2020 Sal 16:58 tarihinde Yusuf <notifications@github.com> şunu yazdı:

**Comment by ybedirhanpak** [comment]
Issue'nun neden iptal edildiğine dair vs. güncelleme yapabiliriz.
